title: Vitorian Steampunk
description: > 
  Arte inspirada na cultura steampunk, aplicada em decoração de alto padrão.
  Experimente um ambiente muito mais sofisticado, com aspecto rústico e elegante
  ao mesmo tempo.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://vitoriansteampunk.com"

# Build settings
markdown: kramdown
exclude:
  - gulpfile.js
  - desktop.ini
  - README.md

collections:
  sections:
    output: false
  produtos:
    output: true
  erros:
    output: true
  
defaults:
  - scope:
      path: ""
      type: produtos
    values:
      layout: produto
  - scope:
      path: ""
      type: posts
    values:
      layout: post
  - scope:
      path: ""
      type: erros
    values:
      layout: page
