title: Vitorian Steampunk
description: > 
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://vitoriansteampunk.com"

# Build settings
markdown: kramdown
exclude:
  - gulpfile.js
  - desktop.ini
  - README.md

collections:
  sections:
    output: false
  produtos:
    output: true
  
defaults:
  - scope:
      path: ""
      type: produtos
    values:
      layout: produto
  - scope:
      path: ""
      type: posts
    values:
      layout: post
