---
title: Vitorian Steampunk
timezone: America/Sao_Paulo
collections:
  posts:
    title: Posts
    output: true
  produtos:
    title: Produtos
    output: true
  sections:
    title: Sections
    output: false
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: produtos
  values:
    layout: produto
    image: 
- scope:
    path: ''
    type: posts
  values:
    layout: post
description: 'Arte inspirada na cultura steampunk, aplicada em decoração de alto padrão. Experimente um ambiente muito mais sofisticado, com aspecto rústico e elegante ao
  mesmo tempo.'
email: eduardo@vitoriansteampunk.com
tel:
  - title: "(11) 9 9555-9624"
    number: "+5511995559624"
baseurl: 
url: http://vitoriansteampunk.com
markdown: kramdown
exclude:
- gulpfile.js
- desktop.ini
- README.md
